### ISSUE TITLE
can using in raspberry pi?

### ISSUE THREAD

**Issue by fers50** [gdahia/high-res-fingerprint-recognition#5]
how about to use CNN in raspberry with fingerprint model R307?

**Comment by gdahia** [comment]
I am not familiar with Raspberry devices, and am unable to help you with that. However, I believe systems that are capable of running CNNs with approximately the same number of parameters as HardNet (the CNN architecture we use) should be ok.

**Comment by fers50** [comment]
ok thank your suggestion, maybe I will try directly to raspberry


thank you!!!!

Pada tanggal Sen, 11 Feb 2019 pukul 22.05 Gabriel Dahia <
notifications@github.com> menulis:
